{{- if .Values.proxy.deployCredentials }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "proxy.labels" . | nindent 4 }}
  name: {{ include "proxy.fullname" $ }}-auth-config
  namespace: {{ .Release.Namespace }}
data:
  authn.yaml: {{ .Values.proxy.credentials | b64enc }}
{{- end }}
