{{- if .Values.proxy.enabled }}
{{- if .Values.proxy.deployCredentials }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "proxy.fullname" $ }}-auth-config
  labels:
    {{- include "proxy.labels" . | nindent 4 }}
data:
  authn.yaml: {{ .Values.proxy.credentials | b64enc }}
{{- end }}
{{- end }}
