{{- if .Values.enabled }}
{{- if and (.Values.networkPolicy.enabled) (eq .Values.networkPolicy.flavor "cilium") }}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  labels:
    {{- include "proxy.labels" . | nindent 4 }}
  name: {{ include "proxy.fullname" $ }}
  namespace: {{ .Release.Namespace }}
spec:
  endpointSelector:
    matchLabels:
      {{- include "proxy.selectorLabels" . | nindent 6 }}
  ingress:
  - toPorts:
    - ports: 
      - port: http
        protocol: TCP
{{- end }}
{{- end }}
