FROM golang:1.23-alpine as builder

ARG VERSION=dev
ARG COMMIT=none

ENV GO111MODULE=on
ENV CGO_ENABLED=0

RUN apk add  -U --no-cache git ca-certificates && \
    mkdir -p src/github.com/giantswarm/grafana-multi-tenant-proxy

WORKDIR /go/src/github.com/giantswarm/grafana-multi-tenant-proxy

COPY go.mod go.mod
COPY go.sum go.sum
COPY cmd cmd
COPY internal internal

RUN go vet ./...

RUN cd cmd/grafana-multi-tenant-proxy && \
    go test -ldflags="-X 'main.version=${VERSION}' -X 'main.commit=${COMMIT}'"

RUN cd cmd/grafana-multi-tenant-proxy && \
    go build -ldflags="-X 'main.version=${VERSION}' -X 'main.commit=${COMMIT}'"

FROM scratch

COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /go/src/github.com/giantswarm/grafana-multi-tenant-proxy/cmd/grafana-multi-tenant-proxy/grafana-multi-tenant-proxy /grafana-multi-tenant-proxy

ENTRYPOINT [ "/grafana-multi-tenant-proxy" ]
