---
version: 2.1

orbs:
  architect: giantswarm/architect@dev:a56ecd2141695f7d18128eb5b7d7c6d5c360578a

workflows:
  build:
    jobs:
    - architect/go-build:
          name: go-build
          binary: grafana-multi-tenant-proxy
          path: ./cmd/grafana-multi-tenant-proxy
          filters:
            tags:
              only: /^v.*/

    - architect/push-to-registries:
          context: architect
          name: push-to-registries
          requires:
            - go-build
          filters:
            tags:
              only: /^v.*/

    - architect/push-to-app-catalog:
          context: "architect"
          executor: "app-build-suite"
          name: push-to-app-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "grafana-multi-tenant-proxy"
          requires:
            - push-to-registries
          filters:
            tags:
              only: /^v.*/

    - architect/push-to-app-collection:
          context: "architect"
          name: capa-app-collection
          app_name: "grafana-multi-tenant-proxy"
          app_namespace: "monitoring"
          app_collection_repo: "capa-app-collection"
          requires:
            - push-to-app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
