---
version: 2.1

orbs:
  architect: giantswarm/architect@5.6.0

workflows:
  build:
    jobs:
     - architect/push-to-registries:
        context: architect
        name: push-to-registries
        image: "giantswarm/grafana-multi-tenant-proxy"
        dockerfile: "build/package/Dockerfile-with-tests"
        filters:
          tags:
            only: /^v.*/
