---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-multi-tenant-proxy-auth-config
  namespace: grafana
  labels:
    app: grafana-multi-tenant-proxy
stringData:
  authn.yaml: |-
    users:
      - username: Tenant1
        password: 1tnaneT
        orgid: tenant-1
      - username: Tenant2
        password: 2tnaneT
        orgid: tenant-2
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-multi-tenant-proxy-config
  namespace: grafana
  labels:
    app: grafana-multi-tenant-proxy
stringData:
  config.yaml: |-
    targetServers:
    - name: "loki-read"
      host: "http://grafana-multi-tenant-proxy.grafana.svc.cluster.local:3100/loki-read"
      target: "http://loki-read.grafana.svc.cluster.local:3100"
    - name: "loki-write"
      host: "http://grafana-multi-tenant-proxy.grafana.svc.cluster.local:3100/loki-write"
      target: "http://loki-write.grafana.svc.cluster.local:3100"
      keepOrgId: true
    - name: "loki-backend"
      host: "http://grafana-multi-tenant-proxy.grafana.svc.cluster.local:3100/loki-backend"
      target: "http://loki-backend.grafana.svc.cluster.local:3100"
      keepOrgId: true
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-multi-tenant-proxy
  namespace: grafana
spec:
  ports:
  - port: 3100
    protocol: TCP
    targetPort: 3100
  selector:
    app: grafana-multi-tenant-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana-multi-tenant-proxy
  name: grafana-multi-tenant-proxy
  namespace: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-multi-tenant-proxy
  strategy: {}
  template:
    metadata:
      labels:
        app: grafana-multi-tenant-proxy
    spec:
      containers:
      - name: grafana-multi-tenant-proxy
        image: giantswarm/grafana-multi-tenant-proxy:dev
        args:
          - "run"
          - "--port=3100"
          - "--auth-config=/etc/loki-multi-tenant-proxy/authn.yaml"
          - "--proxy-config=/etc/loki-multi-tenant-proxy/read-config.yaml"
        ports:
          - name: http
            containerPort: 3100
            protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
          - name: config
            mountPath: /etc/grafana-multi-tenant-proxy
      volumes:
        - name: config
          projected:
            sources:
              - secret:
                  name: loki-multi-tenant-proxy-auth-config
              - configMap:
                  name: loki-multi-tenant-proxy-config
