---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-multi-tenant-proxy-config
  namespace: grafana
  labels:
    app: grafana-multi-tenant-proxy
stringData:
  config.yaml: |-
    targetServerUrl: http://loki.grafana.svc.cluster.local:3100
    authentication:
      users:
        - username: Tenant1
          password: 1tnaneT
          orgid: tenant-1
        - username: Tenant2
          password: 2tnaneT
          orgid: tenant-2
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-multi-tenant-proxy
  namespace: grafana
spec:
  ports:
  - port: 3100
    protocol: TCP
    targetPort: 3100
  selector:
    app: grafana-multi-tenant-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana-multi-tenant-proxy
  name: grafana-multi-tenant-proxy
  namespace: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-multi-tenant-proxy
  strategy: {}
  template:
    metadata:
      labels:
        app: grafana-multi-tenant-proxy
    spec:
      containers:
      - name: grafana-multi-tenant-proxy
        image: giantswarm/grafana-multi-tenant-proxy:dev
        args:
          - "run"
          - "--port=3100"
          - "--config=/etc/grafana-multi-tenant-proxy/config.yaml"
        ports:
          - name: http
            containerPort: 3100
            protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
          - name: config
            mountPath: /etc/grafana-multi-tenant-proxy
      volumes:
        - name: config
          secret:
            secretName: grafana-multi-tenant-proxy-config
